# Generated by Django 4.1.7 on 2023-03-27 10:51

import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Location Name')),
                ('club', models.CharField(max_length=50, verbose_name='Club Name')),
                ('street', models.CharField(max_length=50, verbose_name='Street')),
                ('house_number', models.CharField(max_length=10, verbose_name='House number')),
                ('postal_code', models.CharField(max_length=10, verbose_name='Postal code')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name='Country')),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Event Name')),
                ('start_date', models.DateTimeField(verbose_name='Start Date')),
                ('start_time', models.TimeField(verbose_name='Start Time')),
                ('end_date', models.DateTimeField(verbose_name='End Date')),
                ('persons_needed', models.IntegerField(verbose_name='Persons needed')),
                ('fee_per_person', models.IntegerField(verbose_name='Fees per Person')),
                ('notes', models.TextField(verbose_name='Additional Notes')),
                ('link1_link', models.URLField(verbose_name='Link 1 URL')),
                ('link1_name', models.URLField(verbose_name='Link 1 Name')),
                ('link2_link', models.URLField(verbose_name='Link 2 URL')),
                ('link2_name', models.URLField(verbose_name='Link 2 Name')),
                ('link3_link', models.URLField(verbose_name='Link 3 URL')),
                ('link3_name', models.URLField(verbose_name='Link 3 Name')),
                ('link4_link', models.URLField(verbose_name='Link 4 URL')),
                ('link4_name', models.URLField(verbose_name='Link 4 Name')),
                ('link5_link', models.URLField(verbose_name='Link 5 URL')),
                ('link5_name', models.URLField(verbose_name='Link 5 Name')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='RMS.location', verbose_name='Location')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_selected', models.BooleanField(verbose_name='Selected for Event')),
                ('is_official', models.BooleanField(verbose_name='Selection official')),
                ('is_headreferee', models.BooleanField(verbose_name='Headreferee for Event')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='RMS.event', verbose_name='Event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
