# Generated by Django 4.1.7 on 2023-03-27 10:51

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='E-Mail adress')),
                ('birth_date', models.DateField(null=True, verbose_name='Date of Birth')),
                ('mobile', models.CharField(blank=True, max_length=16, verbose_name='Mobile number')),
                ('allow_Reselection', models.BooleanField(default=True, verbose_name='Allow reselection to similar tournament')),
                ('street', models.CharField(max_length=50, verbose_name='Street')),
                ('house_number', models.CharField(max_length=10, verbose_name='House number')),
                ('postal_code', models.CharField(max_length=10, verbose_name='Postal code')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name='Country')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
